name: Build Backend Docker Image
on:
  push:
    branches: ["master"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: test
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - shell: bash
        run: |
          echo "test"
          docker build -t ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG }} .
          docker push ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG }}