name: Build Backend Docker Image
on:
  push:
    branches: ["master"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: test
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - shell: bash
        run: |
          set -xv
          echo "test"
          docker buildx create --name=container --driver=docker-container --use --bootstrap
          docker buildx build --builder=container -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --push --cache-to type=gha,mode=max --cache-from type=gha .
