name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_TAG: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: niwoerner
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and push
        run: |
          /usr/bin/docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --iidfile /home/runner/work/_temp/docker-actions-toolkit-sCj3vX/iidfile --provenance mode=max,builder-id=https://github.com/nw0rn/openpilot/actions/runs/9147053332 --tag niwoerner/openpilot:test --metadata-file /home/runner/work/_temp/docker-actions-toolkit-sCj3vX/metadata-file --push .