name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_TAG: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: niwoerner
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and push
        run: |
          docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --tag niwoerner/openpilot:test --push .